plugins {
    id "com.android.application"
}

android {
    namespace "com.yass.neonmusic"
    compileSdk 34

    defaultConfig {
        applicationId "com.yass.neonmusic"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
